import Head from 'next/head';

import { Sidebar, Feed, Widgets } from '../components';

export default function Home({ newsResults }) {
  return (
    <div>
      <Head>
        <title>Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen mx-auto">
         {/* Sidebar */}
          <Sidebar />

          {/* Feed */}
          <Feed />

          {/* Widgets */}
          <Widgets newsResults={newsResults.articles} />

          {/* Modal */}
      </main>
    </div>
  )
}

// https://saurav.tech/NewsAPI/top-headlines/category/business/us.json
export async function getServerSideProps() {
  const res = await fetch('https://saurav.tech/NewsAPI/top-headlines/category/business/us.json');
  const newsResults = await res.json();

  if(!newsResults) {
    return {
      notFound: true
    }
  }

    return {
      props: {newsResults}, // will be passed to the page component as props
    }
}
